SportsCompetitionsMVC/SportsCompetitionsMVC/Controllers/CompetitionController.cs
using SportsCompetitions.Models;
using SportsCompetitionsMVC.Models;
using SportsCompetitionsMVC.ViewModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsCompetitionsMVC.Controllers
{
    public class CompetitionController : Controller
    {
        // GET: Competition
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult DisplayEvents()
        {
            List<DisplayEventViewModel> vm = new List<DisplayEventViewModel>();
            using (var db = new ApplicationDbContext())
            {
                var allCompetitions = db.SingleCompetition.Where(n => n.StartDate >= DateTime.Today).ToList();
                foreach (var item in allCompetitions)
                {
                    DisplayEventViewModel _event = new DisplayEventViewModel();
                    _event.Category = item.Category.ToString();
                    _event.CompetitorsCount = item.Users.Count();

                    _event.Image = item.Image;
                    _event.StartDate = item.StartDate;
                    _event.Title = item.Title;
                    _event.Description = item.Description;

                    var _moderator = db.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();
                    try
                    {
                        _event.ModeratorName
                      = $"{_moderator.Informations.FirstName} {_moderator.Informations.LastName}";

                    }
                    catch (Exception)
                    {
                        _event.ModeratorName = "Admin Pawel";
                    }

                    vm.Add(_event);


                }


            }


            return View(vm);
        }
        public ActionResult DisplayEndedEvents()
        {
            List<DisplayEventViewModel> vm = new List<DisplayEventViewModel>();
            using (var db = new ApplicationDbContext())
            {
                var allCompetitions = db.SingleCompetition.Where(n => n.StartDate < DateTime.Today).ToList();
                foreach (var item in allCompetitions)
                {
                    DisplayEventViewModel _event = new DisplayEventViewModel();
                    _event.Category = item.Category.ToString();
                    _event.CompetitorsCount = item.Users.Count();

                    _event.Image = item.Image;
                    _event.StartDate = item.StartDate;
                    _event.Title = item.Title;
                    _event.Description = item.Description;

                    var _moderator = db.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();
                    try
                    {
                        _event.ModeratorName
                      = $"{_moderator.Informations.FirstName} {_moderator.Informations.LastName}";

                    }
                    catch (Exception)
                    {
                        _event.ModeratorName = "Admin Pawel";
                    }

                    vm.Add(_event);


                }


            }


            return View("DisplayEvents", vm);
        }
        [Authorize]
        public ActionResult DisplayYourEvents()
        {
            // uzytkownik i jego eventy
            //trzeba zrobic widok z evetami urzytkownika 
            List<DisplayEventViewModel> vm = new List<DisplayEventViewModel>();
            using (var db = new ApplicationDbContext())
            {
                var userCompetitions = db.Users.Include(n => n.SingleCompetition).Where(n => n.UserName == User.Identity.Name).First();

                var competitions = userCompetitions.SingleCompetition.Where(n => n.StartDate >= DateTime.Today);


                foreach (var item in competitions)
                {
                    DisplayEventViewModel _event = new DisplayEventViewModel();
                    _event.Category = item.Category.ToString();
                    _event.CompetitorsCount = item.Users.Count();
                    _event.Image = item.Image;
                    _event.StartDate = item.StartDate;
                    _event.Title = item.Title;
                    _event.Description = item.Description;

                    var _moderator = db.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();
                    _event.ModeratorName
                        = $"{_moderator.Informations.FirstName} {_moderator.Informations.LastName}";

                    vm.Add(_event);


                }





            }
            return View(vm);
        }

        [Authorize]
        public ActionResult DisplayYourEvents(int id)
        {
            return View();
        }

        [Authorize]
        [Authorize(Roles = "Moderator")]
        public ActionResult Create()
        {

            return View(new CompetitonViewModel());
        }
        [HttpPost]
        [Authorize(Roles = "Moderator")]
        public ActionResult Create(CompetitonViewModel viewModel, string type)
        {

            if (ModelState.IsValid)
            {

                var _event = new Competition();



                var serverPath = Server.MapPath("~/Content/Upload/");
                var filename = Guid.NewGuid().ToString();
                var extension = System.IO.Path.GetExtension(viewModel.Image.FileName);

                _event.Image = "/Content/Upload/" + filename + extension;

                Directory.CreateDirectory(serverPath);
                viewModel.Image.SaveAs(serverPath + filename + extension);

                UpdateModel(_event);

                ApplicationUser _dbUser;
                Competition newCompetiton = new Competition();
                using (var db = new ApplicationDbContext())
                {
                    _dbUser = db.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();

                    newCompetiton = _event;
                    newCompetiton.Image = "/Content/Upload/" + filename + extension;
                    newCompetiton.ModeratorId = _dbUser.Id;
                    //newCompetiton.CompetitorsId = new List<string>();


                    db.SingleCompetition.Add(newCompetiton);


                    db.SaveChanges();
                }

            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [Authorize(Roles = "Moderator")]
        public ActionResult SetResults()
        {
            List<DisplayEventViewModel> vm = new List<DisplayEventViewModel>();
            using (var db = new ApplicationDbContext())
            {
                var allCompetitions = db.SingleCompetition.Where(n => n.StartDate < DateTime.Today).ToList();
                foreach (var item in allCompetitions)
                {
                    DisplayEventViewModel _event = new DisplayEventViewModel();
                    _event.Category = item.Category.ToString();
                    _event.CompetitorsCount = item.Users.Count();

                    _event.Image = item.Image;
                    _event.StartDate = item.StartDate;
                    _event.Title = item.Title;
                    _event.Description = item.Description;

                    var _moderator = db.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();
                    try
                    {
                        _event.ModeratorName
                      = $"{_moderator.Informations.FirstName} {_moderator.Informations.LastName}";

                    }
                    catch (Exception)
                    {
                        _event.ModeratorName = "Admin Pawel";
                    }

                    vm.Add(_event);


                }


            }


            return View(vm);
        }
        [Authorize]
        [Authorize(Roles = "Moderator")]
        public ActionResult SetResultsPost(int id)
        {
            


            return View(new ResultViewmodel());
        }

        [Authorize]
        public ActionResult Join(int id)
        {

            // wyslij email do zalogowanego uzytkownika z kodem qr


            ApplicationUser _dbUser;
            using (var db = new ApplicationDbContext())
            {
                _dbUser = db.Users.Include(n => n.SingleCompetition).Where(x => x.UserName == User.Identity.Name).FirstOrDefault();

                Competition _competition = db.SingleCompetition.First(n => n.Id == id);

                //if (_dbUser.SingleCompetition == null)
                //{
                //    _dbUser.SingleCompetition.
                //}

                if (_competition.Users.First(n => n.Id == _dbUser.Id) != null)
                {
                    //tutaj zrobić żeby dało jakis bład że użytkownik już dołączył

                    return RedirectToAction("DisplayYourEvents");
                }

                _competition.Users.Add(_dbUser);
                _dbUser.SingleCompetition.Add(_competition);




                db.SaveChanges();
            }



            return RedirectToAction("DisplayYourEvents");
        }
        public ActionResult JoinSingle()
        {
            List<Competition> _single = new List<Models.Competition>();
            return View();
        }
        public ActionResult JoinTeam()
        {
            List<Competition> _single = new List<Models.Competition>();
            return View();
        }

    }
}

SportsCompetitionsMVC/SportsCompetitionsMVC/Controllers/HomeController.cs
using SportsCompetitions.Models;
using SportsCompetitionsMVC.Models;
using SportsCompetitionsMVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsCompetitionsMVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {

            List<DisplayEventViewModel> vm = new List<DisplayEventViewModel>();
            using (var db = new ApplicationDbContext())
            {
                DateTime today = DateTime.Now;

              
                    var min = db.SingleCompetition.Where(n => n.StartDate >= DateTime.Today).OrderBy(cv => cv.StartDate).Take(3);

                    //var allCompetitions = db.SingleCompetition.Select((s => s.OrderByD=> x.Datescending(x e).FirstOrDefault());
                    foreach (var item in min)
                    {

                        DisplayEventViewModel _event = new DisplayEventViewModel();
                        _event.Title = item.Title;
                        //_event.ModeratorName = (item as SingleCompetition).ModeratorId;
                        _event.Category = item.Category.ToString();
                        _event.CompetitorsCount = item.Users.Count();
                        _event.Image = item.Image;
                        _event.StartDate = item.StartDate;
                        _event.Description = item.Description;
                        _event.ID = item.Id;

                        vm.Add(_event);


                    }

              
                     
               
              


            }

            return View(vm);
        }
    }
}

SportsCompetitionsMVC/SportsCompetitionsMVC/Views/Home/Index.cshtml
@using SportsCompetitionsMVC.ViewModels
@model List<SportsCompetitionsMVC.ViewModels.DisplayEventViewModel>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <img src="~/Images/one.jpeg" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Zawody sportowe.</h1>
                    <p>Weź udział w zawodach i zarejestruj się już dziś!</p>
                    <p><a class="btn btn-lg btn-primary" href="@Url.Action("Register","Account")" role="button">Zarejestruj się</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Images/three.jpg" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1 style="font-size:60px">Sprawdź nadchodzące wydarzenia.</h1>
                    <p>Kliknij aby zobaczyć nadchodzące wydarzenia</p>
                    <p><a class="btn btn-lg btn-primary" href="@Url.Action("DisplayEvents","Competition")" role="button">Wyświetl</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Images/four.jpg" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Zobacz zakończone zawody</h1>
                    <p>Jeśli przegapiłeś swoje zawody lub chcesz zobaczyć te zakończone klinkij.</p>
                    <p><a class="btn btn-lg btn-primary" href="@Url.Action("DisplayEndedEvents","Competition")" role="button">Pokaż zakończone zawody</a></p>
                </div>
            </div>
        </div>
    </div>
    
</div><!-- /.carousel -->


<!-- Marketing messaging and featurettes
    ================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->



<div id="containerMin">

    <div class="container marketing" id="conMain">


        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <div class="row">
            @foreach (var item in Model)
            {

                <div class="col-md-4">
                    <div class="column">

                        <!-- Post-->
                        <div class="post-module" id="main">
                            <!-- Thumbnail-->
                            <div class="thumbnail">
                                <div class="date">
                                    <a href="@Url.Action("Join","Competition",new { id = @item.ID })">

                                        <div class="day"><i class="fa fa-bars" aria-hidden="true"></i></div>
                                    </a>
                                </div>
                                <img src="@item.Image" class="img-responsive" alt="">
                            </div>
                            <!-- Post Content-->
                            <div class="post-content">
                                <div class="category">@item.Category</div>
                                <h1 class="title">@item.Title</h1>
                                <h2 class="sub_title"> @item.StartDate</h2>
                                <p class="description">@item.Description</p>
                                <div class="post-meta"><span class="timestamp"><i class="fa fa-clock-">o</i> 6 mins ago</span><span class="comments"><i class="fa fa-comments"></i><a href="#"> @item.CompetitorsCount zapisanych uczestników</a></span></div>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>




    </div>
    <div id="content">
        <div id="content5">

            <h3><i class="fa fa-child" style="font-size:40px"></i>Wypróbuj już dzisiaj</h3>
            <p>
                Nigdy wcześniej organizacja zawodów, imprez i wydarzeń nie była tak prosta.

            </p>
        </div>
        <div id="content1">
            <i class="fa fa-thumbs-up" style="font-size:30px"></i>
            <h3>Prostota obsługi</h3>
            <p>
                Zarówno panel administracyjny wydarzenia, jak i formularz rejestracji (formularz zgłoszeniowy) uczestnika cechuje prostota i użyteczność.

            </p>
        </div>

        <div id="content2">
            <i class="fa fa-hourglass-3" style="font-size:30px"></i>
            <h3>Oszczędność czasu</h3>
            <p>
                Dzięki pełnej automatyzacji procesu rejestracji.

            </p>
        </div>
        <div style="clear:both"></div>
        <div id="content3">


            <i class="fa fa-envelope" style="font-size:30px"></i>
            <h3> Powiadomienia mailowe</h3>
            <p>

                Zostajesz powiadamiany o każdej rejestracji, dzięki czemu jesteś zawsze na bieżąco.
            </p>
        </div>
        <div id="content4">
            <i class="fa fa-mobile" style="font-size:40px"></i>
            <h3>Kod QR</h3>
            <p>
                Przy rejestracji otrzymujesz kod QR, który będziesz wykorzystywać do dalszego uczestnictwa w zawodach.

            </p>
        </div>
        <div style="clear:both"></div>


    </div>
</div>
<div style="clear:both"></div>
<footer>
    &reg; Paweł Płowucha, Grzegorz Chmura, Arkadiusz Zwardoń, Mateusz Przbyło, Jakub Kubala
</footer>
<script>
    $(window).load(function () {
        $('.post-module').hover(function () {
            $(this).find('.description').stop().animate({
                height: "toggle",
                opacity: "toggle"
            }, 300);
        });
    });
</script>